spring:
  security:
    oauth2:
      resourceserve:
        jwt:
          issue-uri: http://localhost:9999/auth/realms/one
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
