spring:
  security:
    oauth2:
      resourceserve:
        opaque-token:
          introspection-uri: http://localhost:9999/auth/realms/one/protocol/openid-connect/token/introspect
          client-id: app
          client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a
        #jwt:
          #issuer-uri: http://localhost:9999/auth/realms/one
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
